server:
  port: 8090

spring:
  application:
    name: msvc-productmanagement
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@hitoprogramacion.k3gaujt.mongodb.net/?retryWrites=true&w=majority&appName=HitoProgramacion
      database: HitoProgramacion

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka