eureka:
  client:
    register-with-eureka: false

server:
  port: 8081

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: http://localhost:8090
          predicates:
            - Path=/api/products/**
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: http://localhost:9090
          predicates:
            - Path=/api/user/**